### ISSUE TITLE
pydicom version

### ISSUE THREAD

**Issue by koflera** [PTB-MR/mrpro#684]
pydicom 2.3 from our requirements results in
>       dataset.save_as(self.filename, enforce_file_format=True)
E       TypeError: Dataset.save_as() got an unexpected keyword argument 'enforce_file_format'

in the tests. we might need a newer pydicom version. 

-Felix

#361

**Comment by koflera** [comment]
It works with the current latest pydicom 3.0.1 (and maybe also older versions)
